name: CI

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.26
      - run: bun install --no-save

      # Run Turbo
      - name: Build
        run: bunx turbo run build
